{{- if .Values.serviceAccount.create -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "clipper.serviceAccountName" . }}
  labels:
{{ include "clipper.labels" . | nindent 4 }}
{{- end -}}
